name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: build-debs-dpkg
  # You may pin to the exact commit or the version.
  # uses: shumailaahmed/build-deb-action@11058815a9e1bb20262bcd64df40df074825a77c
      uses: shumailaahmed/build-deb-action@v1.0.2
      with:
        # Package name of debian package.
        package: "nbfc-linux"
        # Directory of release files.
        package_root: "./"
        # Package maintainer name.
        maintainer: "NBFC"
        # Package version.
        version: "1.0.0"
        # Package installed size. GitHub Actions set summarized byte size of `package_root` directory when this parameter is empty.
        installed_size: "" # optional, default is 
        # Package dependencies.
        depends: "lm-sensors"# optional, default is none
        # Package architecture.
        arch: "amd64"# optional, default is amd64
        # Package description.
        desc: "Notebook Fan Control - app for controlling fan on most of the notebooks"# optional, default is no description
